### ISSUE TITLE
Changing labels in compose config should update the jobs

### ISSUE THREAD

**Issue by vitoyucepi** [funkyfuture/deck-chores#114]
## Summary
If I change the time interval in `compose.yaml`, the job is not rescheduled.
If I change the command in `compose.yaml`, the job command doesn't change.

## Reproduction
1. Start deck-chores `docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e TZ=UTC funkyfuture/deck-chores:1.3.10`.
1. Create two compose configs for the same server.
   `compose1.yaml`
   ```yaml
   services:
     test:
       image: alpine:3.17
       labels:
         deck-chores.test.command: env
         deck-chores.test.interval: every minute
       command: sleep 1000
       stop_grace_period: 1s
   ```
   `compose2.yaml`
   ```yaml
   services:
     test:
       image: alpine:3.17
       labels:
         deck-chores.test.command: echo 1
         deck-chores.test.interval: every second
       command: sleep 1000
       stop_grace_period: 1s
   ```
1. Run command `docker-compose -f compose1.yaml up -d; docker-compose -f compose2.yaml up -d`.

## Expected behavior

After changing labels and redeploying, jobs should change.

## Actual behavior

After changing labels and redeploying, jobs remain the same.

## Versions
- docker: *20.10.23*
- docker-compose: *2.16.0*
- deck-chores: *1.3.10*

## Additional
Maybe related to #113.
