### ISSUE TITLE
Job not triggered with docker swarm

### ISSUE THREAD

**Issue by biellsilva5** [funkyfuture/deck-chores#143]
Sorry if this is not a problem, but rather a bad configuration.
My environment is with docker swarm.
I have a stack for the deck-chores:
deck-chores-stack.yml
```yml
version: '3'

services:
  cronjob_officer:
    image: funkyfuture/deck-chores:1.3
    environment:
      TIMEZONE: America/Sao_Paulo
      DEFAULT_FLAGS: noservice
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cronjob_officer_network
    deploy:
      mode: global  
      resources:
          limits:
            cpus: '0.2'
            memory: 512M

networks:
  cronjob_officer_network:
    external: true
```

cronjob_officer_network driver is: overlay

I have another stack with my application:
my-application-stack.yml
```yml
version: '3'
services:
  my_application:
    image: ...
    networks:
      - my_application_network
      - postgres01_network
      - traefik_public
      - cronjob_officer_network
    environment:
      ...
    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.5'
            memory: 1024M
      labels:
          - deck-chores.import-files.command=python manage.py import_files 
          - deck-chores.import-files.interval='every minute'
          ...


networks:
  my_application_network:
    external: true
  traefik_public:
    external: true
  postgres01_network:
    external: true
  cronjob_officer_network:
    external: true
```

My application has the same network as the deck-chores network.

However, I was unsuccessful in triggering the jobs created through my application.

Deck-chores logs:
```log
Deck Chores 1.3.23 started.
2024-04-28 00:17:20,186|INFO    |Inspecting running containers.
2024-04-28 00:17:20,583|INFO    |Listening to events.
```

**Comment by biellsilva5** [comment]
After trying so hard.
I found the problem in my application stack.
I had to put labels outside of deploy.
going as follows:

```yml
version: '3'
services:
  my_application:
    image: ...
    networks:
      - my_application_network
      - postgres01_network
      - traefik_public
      - cronjob_officer_network
    environment:
      ...
    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.5'
            memory: 1024M
       labels:
         ...#labels for traefik and others
    labels:
      - deck-chores.import-files.command=python manage.py import_files 
      - deck-chores.import-files.interval=every minute
         


networks:
  my_application_network:
    external: true
  traefik_public:
    external: true
  postgres01_network:
    external: true
  cronjob_officer_network:
    external: true
```
