### ISSUE TITLE
[BUG] Example for name in RTD does not comply with regex for "name" 

### ISSUE THREAD

**Issue by tabedzki** [funkyfuture/deck-chores#146]
## Bug

If one uses the example (copied below) for labels from the [deck-chores website](https://deck-chores.readthedocs.io/en/stable/usage.html#containers-without-an-enduring-main-process), one ends up with an error related to the `_` in the example (see below).

Reproduced Code:
```yaml
services:
  neverending:
    # …
    command: tail -f /dev/null
    labels:
      deck-chores.daily_job.command: daily_command …
      deck-chores.daily_job.interval: daily
```

Error:
```
2024-10-12 09:30:51,064|ERROR   |Misconfigured job definition: {'command': 'sh -c "echo \'Hello\' " &> /proc/1/fd/1', 'interval': 'daily', 'name': 'daily_job', 'user': ''}
2024-10-12 09:30:51,064|ERROR   |Errors: {'name': ["value does not match regex '[a-z0-9-]+'"]}
```

## Possible solutions
1. Update the [name regex](https://github.com/funkyfuture/deck-chores/blob/2f48370b444ea5ba24eb29421f367db63ece35c0/deck_chores/config.py#L73) (`[a-z0-9-]+`)  to account for a `_` as provided in the example
2. Update the example be updated to use `-` instead

Which one do you think is a better fix? I personally like idea 1 of making the regex more robust.
