### ISSUE TITLE
job config considered invalid 

### ISSUE THREAD

**Issue by 0xj9** [funkyfuture/deck-chores#20]
i have these services running on my system. based on the docs this should work:

```yml
version: '2'
services:
  db:
    image: postgres:alpine
    volumes:
      - /snapshot
      - /var/lib/postgresql/data
    labels:
      deck-chores.snapshot.command: sh -c "nice -n 19 pg_dump -Z 9 -U foo bar -f /snapshot/`date -I`.dump.gz"
      deck-chores.snapshot.interval: daily
  officer:
    image: funkyfuture/deck-chores
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

however, what i get is this error message:

```
officer_1         | 2017-06-22 16:10:43,427|INFO    |Listening to events.
officer_1         | 2017-06-22 16:10:43,428|INFO    |Inspecting running containers.
officer_1         | 2017-06-22 16:10:43,447|INFO    |Locking service id: 698d4e22-6668-5ffe-84e8-cc7e8594e95d
officer_1         | 2017-06-22 16:10:43,449|INFO    |Added 'snapshot' for /project_db_1
officer_1         | 2017-06-22 16:10:43,509|ERROR   |Misconfigured job definition: {'interval': 'daily', 'name': 'shapshot'}
officer_1         | 2017-06-22 16:10:43,509|ERROR   |Errors: {'command': ['required field']}
officer_1         | 2017-06-22 16:10:43,514|ERROR   |Misconfigured job definition: {'command': 'sh -c "nice -n 19 pg_dump -Z 9 -U foo bar -f /snapshot/`date -I`.dump.gz"', 'name': 'snapshot'}
officer_1         | 2017-06-22 16:10:43,514|ERROR   |Errors: {'cron': ['required field'], 'date': ['required field'], 'interval': ['required field']}
```
