### ISSUE TITLE
Multiple Jobs

### ISSUE THREAD

**Issue by leew** [funkyfuture/deck-chores#21]
I am trying to have multiple jobs scheduled using deck-chores, is this possible.
```yml
services:
     db: 
         image: mongo
         labels:
             deck-chores.dump.command: sh -c "mongodump --db <database> --gzip --archive=/data/backups/$$(date -Idate).gz"
            deck-chores.dump.cron: "* * * * * * */1 0"

      website:
         image: my-image
         labels:
             deck-chores.generate-report.command: <Some task>
            deck-chores.generate-report.cron: "* * * * * * */10 0"
```
But deckchores log only prints that it is adding the job for the website service.

I have tried having multiple deckchores running, but this seems expensive for having multiple tasks scheduled. 

I couldn't see anything in the documentation that says that this isn't possible, but then again, I could see anything that says this is possible.
