### ISSUE TITLE
cron trigger parser is broken

### ISSUE THREAD

**Issue by qmnonic** [funkyfuture/deck-chores#44]
**Found in** version 0.2, and still exists in 0.3.

**Description:**
Cron triggers don't work because the code parsing the trigger definition has a bug.

For example, if i specify a cron trigger as documented, or any arrangement of cron statements, it fails with an error.  

2 Examples below:

```
deck-chores    | Deck Chores 0.3 started.
deck-chores    | 2019-02-27 18:05:15,843|INFO    |Inspecting running containers.
deck-chores    | 2019-02-27 18:05:15,857|INFO    |Listening to events.
deck-chores    | 2019-02-27 18:05:15,936|ERROR   |Misconfigured job definition: {'command': '/bin/sh -c "cd /some/path; execute_this"', 'cron': '"0 0 7 3 0"', 'user': 'root', 'name': 'refresh-data'}
deck-chores    | 2019-02-27 18:05:15,936|ERROR   |Errors: {'cron': ['Error while instantiating a CronTrigger with \'(\'*\', \'*\', \'*\', \'"0\', \'0\', \'7\', \'3\', \'0"\')\'.']}
```

```
2019-02-27T16:43:59.269614536Z 2019-02-27 16:43:59,269|ERROR   |Misconfigured job definition: {'command': '/bin/sh -c "cd /some/path; execute_this"', 'cron': '"* * * * * 8 9 0"', 'user': 'root', 'name': 'refresh-data'}
2019-02-27T16:43:59.269992640Z 2019-02-27 16:43:59,269|ERROR   |Errors: {'cron': ['Error while instantiating a CronTrigger with \'(\'"*\', \'*\', \'*\', \'*\', \'*\', \'8\', \'9\', \'0"\')\'.']}
```

I'm not a python dev, but I can see the error is a result of the `_fill_args` function:
```
    def _normalize_coerce_cron(self, value: str) -> Tuple[Type, Tuple[str, ...]]:
        args = self._fill_args(value, CRON_TRIGGER_FIELDS_COUNT, '*')
        return CronTrigger, args
```

Because if i replace it with this, and specify the correct number of cron fields (`* * * * * 8 * *`) it works fine.
```
    def _normalize_coerce_cron(self, value: str) -> Tuple[Type, Tuple[str, ...]]:
        return CronTrigger, value.split(' ')
```

**Comment by funkyfuture** [comment]
ciao, how do you configure the container? there are some surplus quotes in this value: `
'"0 0 7 3 0"`'

**Comment by qmnonic** [comment]
I tried with quotes `"0 0 7 3 0"`, without quotes `0 0 7 3 0`, individual quotes '"0" "0" "7" "3" "0"` with various styles of cron examples.  None worked.

You'll notice in the logging statements that `_fill_args` doesn't actually prepend `*`s properly in the list/tuple - see the `"` in the 4th position and at the end?
`\'(\'*\', \'*\', \'*\', \'"0\', \'0\', \'7\', \'3\', \'0"\')\'.']}`

**Comment by funkyfuture** [comment]
in order to replicate what you experience i need the information how you configure the container in question. please post the `docker-compose.yml`, your command call or whatever else you're doing.

also, complete logs at debug level are always helpful.

**Comment by qmnonic** [comment]
relevant parts of the docker-compose.yml
```
  # execute jobs in this container, timezone is UTC
  shiny-jobs:
    container_name: shiny-jobs
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    user: 'root'
    volumes:
       ... stuff here ...
    environment:
      - R_LIBS='/srv/library'
    labels:
      - deck-chores.refresh.command=/bin/sh -c "cd /srv/server/app; update_data.sh"
      - deck-chores.refresh.cron=* * * * * 8 0 0
      - deck-chores.refresh.user=root

  # cron jobs..
  deck-chores:
    image: funkyfuture/deck-chores:0.3
    container_name: deck-chores
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TIMEZONE: UTC
```

I don't have debug logs, the logs above should be enough.
I'm fairly certain cron won't work in any configuration.
