### ISSUE TITLE
Suddently stops working

### ISSUE THREAD

**Issue by Silex** [funkyfuture/deck-chores#56]
Hello,

Not sure I can debug this but I had this very weird bug happening suddenly out of the blue:

```
^[[36mofficer_1   |^[[0m 2020-04-09 11:50:07,575|INFO    |W, [2020-04-09T11:50:05.128761 #29290]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:364) 
^[[36mofficer_1   |^[[0m 2020-04-09 11:50:07,576|INFO    |W, [2020-04-09T11:50:05.129211 #29290]  WARN -- : DEPRECATION WARNING: Using a dynamic :action segment in a route is deprecated and will be removed in Rails 6.0. (called from instance_eval at /usr/src/redmine/config/routes.rb:364) 
^[[36mofficer_1   |^[[0m 2020-04-09 11:50:07,576|INFO    |== END of captured stdout & stderr ==== 
^[[36mofficer_1   |^[[0m 2020-04-09 11:55:00,004|INFO    |redmine_web_1: Executing 'read-helpdesk-emails'. 
^[[36mofficer_1   |^[[0m Execution of job "exec_job (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='*', minute='*/5', second='0'], next run at: 2020-04-09 12:00:00 CEST)" skipped: maximum number of running instances reached (1) 
^[[36mofficer_1   |^[[0m Error notifying listener 
^[[36mofficer_1   |^[[0m Traceback (most recent call last): 
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 831, in _dispatch_event 
^[[36mofficer_1   |^[[0m     cb(event) 
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/deck_chores/jobs.py", line 37, in on_max_instances 
^[[36mofficer_1   |^[[0m     definition = job.kwargs 
^[[36mofficer_1   |^[[0m AttributeError: 'dict' object has no attribute 'kwargs' 
^[[36mofficer_1   |^[[0m Execution of job "exec_job (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='*', minute='*/5', second='0'], next run at: 2020-04-09 12:05:00 CEST)" skipped: maximum number of running instances reached (1) 
^[[36mofficer_1   |^[[0m Error notifying listener 
^[[36mofficer_1   |^[[0m Traceback (most recent call last): 
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 831, in _dispatch_event 
^[[36mofficer_1   |^[[0m     cb(event) 
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/deck_chores/jobs.py", line 37, in on_max_instances 
^[[36mofficer_1   |^[[0m     definition = job.kwargs 
^[[36mofficer_1   |^[[0m AttributeError: 'dict' object has no attribute 'kwargs' 
^[[36mofficer_1   |^[[0m Execution of job "exec_job (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='*', minute='*/5', second='0'], next run at: 2020-04-09 12:10:00 CEST)" skipped: maximum number of running instances reached (1)
^[[36mofficer_1   |^[[0m Error notifying listener
^[[36mofficer_1   |^[[0m Traceback (most recent call last):
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 831, in _dispatch_event
^[[36mofficer_1   |^[[0m     cb(event)
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/deck_chores/jobs.py", line 37, in on_max_instances
^[[36mofficer_1   |^[[0m     definition = job.kwargs
^[[36mofficer_1   |^[[0m AttributeError: 'dict' object has no attribute 'kwargs'
^[[36mofficer_1   |^[[0m Execution of job "exec_job (trigger: cron[year='*', month='*', day='*', week='*', day_of_week='*', hour='*', minute='*/5', second='0'], next run at: 2020-04-09 12:15:00 CEST)" skipped: maximum number of running instances reached (1)
^[[36mofficer_1   |^[[0m Error notifying listener
^[[36mofficer_1   |^[[0m Traceback (most recent call last):
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 831, in _dispatch_event
^[[36mofficer_1   |^[[0m     cb(event)
^[[36mofficer_1   |^[[0m   File "/usr/local/lib/python3.7/site-packages/deck_chores/jobs.py", line 37, in on_max_instances
^[[36mofficer_1   |^[[0m     definition = job.kwargs
```

My docker-compose:

``` yaml
version: '3.7'
services:
  web:
    image: redmine:4.1.1-passenger
    (snip)
    labels:
      deck-chores.reminder-emails.command: rake redmine:send_reminders
      deck-chores.reminder-emails.cron: 'mon 4 0 0'
      deck-chores.read-helpdesk-emails.command: rake redmine:email:helpdesk:receive
      deck-chores.read-helpdesk-emails.cron: '*/5 0'

  officer:
    image: funkyfuture/deck-chores:1
    restart: always
    environment:
      TZ: Europe/Zurich
      TIMEZONE: Europe/Zurich
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

The error message is weird, can you explain what it means?
