### ISSUE TITLE
Python error with linux/arm/v7

### ISSUE THREAD

**Issue by cybermcm** [funkyfuture/deck-chores#74]
Possible issue? Trying it with RaspberryOS (current image)
error:
```
cron          | Fatal Python error: init_interp_main: can't initialize time
cron          | Python runtime state: core initialized
cron          | PermissionError: [Errno 1] Operation not permitted
cron          |
cron          | Current thread 0xb6fd9390 (most recent call first):
cron          | <no Python frame>
```
my compose:
```
cron:
  container_name: cron
  environment:
   - TIMEZONE=Europe/Vienna
  image: funkyfuture/deck-chores:1
  networks:
   - compose
  restart: always
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock
```
```
root@raspi03:/opt# uname -a
Linux raspi03 5.10.52-v7l+ #1440 SMP Tue Jul 27 09:55:21 BST 2021 armv7l GNU/Linux
```
If you need any additional info, I'm happy to provide it.
